defaults: &defaults
  machine:
    image: circleci/classic:201711-01
    docker_layer_caching: true
  working_directory: ~/courses


version: 2

jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Building and pushing docker images
          command: |
            make build_and_push_docker_quora

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          context: org-global
